import type { LifeHelperRequest } from "./types";

export const sampleLifeHelperRequests: LifeHelperRequest[] = [
  {
    id: "sample-cleaning-ikebukuro",
    area: "池袋",
    authorId: "sample-author-cleaning",
    authorName: "Japan Life 示例用户",
    budget: "2,000-4,000円参考",
    category: "cleaning",
    contact: "",
    contactVisibility: "after_apply",
    createdAt: "本地示例",
    description: "小房间整理、扫地、倒垃圾和简单收纳。希望先确认时间、范围和需要自带的清洁用品。",
    preferredTime: "今天傍晚",
    source: "sample",
    status: "open",
    title: "小房间清洁整理",
  },
  {
    id: "sample-procedure-shinjuku",
    area: "新宿",
    authorId: "sample-author-procedure",
    authorName: "Japan Life 示例用户",
    budget: "报酬面议",
    category: "procedure",
    contact: "",
    contactVisibility: "after_apply",
    createdAt: "本地示例",
    description: "想找懂日语的人一起去窗口确认材料。不代办重要签字，只做翻译和流程陪同。",
    preferredTime: "工作日上午",
    source: "sample",
    status: "open",
    title: "区役所手续陪同",
  },
  {
    id: "sample-furniture-nakano",
    area: "中野",
    authorId: "sample-author-furniture",
    authorName: "Japan Life 示例用户",
    budget: "3,000円起参考",
    category: "furniture",
    contact: "",
    contactVisibility: "after_apply",
    createdAt: "本地示例",
    description: "小书架和桌子组装，最好有简单工具。搬重物或上门时间需要提前确认。",
    preferredTime: "周末",
    source: "sample",
    status: "open",
    title: "家具组装帮忙",
  },
  {
    id: "sample-pet-kichijoji",
    area: "吉祥寺",
    authorId: "sample-author-pet",
    authorName: "Japan Life 示例用户",
    budget: "1,500-3,000円参考",
    category: "pet",
    contact: "",
    contactVisibility: "after_apply",
    createdAt: "本地示例",
    description: "短时间喂食和确认饮水，不涉及医疗判断。进房间前需要双方确认身份和细节。",
    preferredTime: "明天下午",
    source: "sample",
    status: "open",
    title: "猫咪临时照看",
  },
];
