import type { TrainDeal, TrainDealInfoConfidence, TrainDealTab } from "@/lib/trainDeals/types";

export const trainDealTabs: TrainDealTab[] = ["全部", "一日券", "东京 Metro", "都营地下铁", "JR", "私铁", "机场交通", "观光", "学生 / 通勤"];

const priceNote = "价格可能变化，请以官方信息为准。";
const purchaseNote = "购买地点、使用条件和有效区间请以铁路公司官方信息为准。";

function deal(input: Omit<TrainDeal, "infoConfidence" | "lastCheckedLabel" | "priceNote" | "purchaseNote"> & { infoConfidence?: TrainDealInfoConfidence; lastCheckedLabel?: string }): TrainDeal {
  return {
    ...input,
    infoConfidence: input.infoConfidence ?? "中",
    lastCheckedLabel: input.lastCheckedLabel ?? "价格和适用范围可能变化",
    priceNote,
    purchaseNote,
  };
}

export const trainDeals: TrainDeal[] = [
  deal({
    id: "tokyo-metro-24h",
    name: "東京メトロ24時間券",
    company: "Tokyo Metro",
    category: "东京 Metro",
    area: "东京 Metro 全线",
    priceLabel: "购买前请确认官方价格",
    validFor: "启用后一定时间内可在东京 Metro 线路内使用",
    bestFor: "一天内主要坐 Metro、换乘次数较多",
    description: "适合在银座、表参道、上野、池袋等 Metro 覆盖区域之间移动。",
    caution: "不覆盖都营地下铁、JR 和多数私铁路线。",
    officialSearchQuery: "東京メトロ24時間券 公式",
    infoConfidence: "高",
    lastCheckedLabel: "需购买前确认",
    goodFor: ["一天坐多次地铁", "东京市区移动", "Metro 路线较多"],
    notGoodFor: ["只坐 1〜2 次", "主要坐 JR", "路线不在 Metro 范围"],
    tags: ["一日券", "Metro", "市区移动"],
  }),
  deal({
    id: "toei-marugoto-kippu",
    name: "都営まるごときっぷ",
    company: "東京都交通局",
    category: "都营地下铁",
    area: "都营地下铁、都营巴士等指定范围",
    priceLabel: "购买前请确认官方价格",
    validFor: "指定日期内在适用范围内使用",
    bestFor: "主要坐都营线，或搭配都营巴士移动",
    description: "适合浅草、门前仲町、新宿线沿线等都营线路为主的一日行程。",
    caution: "不同票种适用交通范围不同，购买前请确认官方说明。",
    officialSearchQuery: "都営まるごときっぷ 公式",
    infoConfidence: "高",
    goodFor: ["都营地下铁较多", "搭配都营巴士", "东京市区观光"],
    notGoodFor: ["主要坐 Metro", "主要坐 JR", "只在一个车站附近活动"],
    tags: ["一日券", "都营", "巴士"],
  }),
  deal({
    id: "metro-toei-common-one-day",
    name: "東京メトロ・都営地下鉄共通一日乗車券",
    company: "Tokyo Metro / 東京都交通局",
    category: "一日券",
    area: "东京 Metro + 都营地下铁",
    priceLabel: "购买前请确认官方价格",
    validFor: "指定日期内在东京主要地下铁范围使用",
    bestFor: "Metro 和都营地下铁都会坐的一天",
    description: "适合地下铁为主、但不确定会坐 Metro 还是都营的市区移动。",
    caution: "不覆盖 JR 和多数私铁，跨公司路线要先看清楚。",
    officialSearchQuery: "東京メトロ 都営地下鉄 共通一日乗車券 公式",
    infoConfidence: "高",
    goodFor: ["一天坐多次地铁", "东京市区观光", "Metro 和都营混坐"],
    notGoodFor: ["JR 区间较多", "私铁路线较多", "只坐 1〜2 次"],
    tags: ["一日券", "Metro", "都营"],
  }),
  deal({
    id: "tokyo-subway-ticket",
    name: "Tokyo Subway Ticket",
    company: "Tokyo Metro / 都营地下铁",
    category: "观光",
    area: "东京 Metro + 都营地下铁",
    priceLabel: "价格可能变化，请以官方信息为准",
    validFor: "常见为 24 / 48 / 72 小时类型，请确认购买条件",
    bestFor: "观光、短期多点移动、地下铁为主",
    description: "覆盖东京主要地下铁网络，适合一天去多个市区景点。",
    caution: "购买资格和购买地点可能有限制，不覆盖 JR。",
    officialSearchQuery: "Tokyo Subway Ticket 公式",
    infoConfidence: "高",
    goodFor: ["东京市区观光", "一天坐多次地铁", "短期旅行"],
    notGoodFor: ["主要坐 JR", "长期通勤", "路线不在地下铁范围"],
    tags: ["一日券", "观光", "Metro", "都营"],
  }),
  deal({
    id: "tokunai-pass",
    name: "JR 都区内パス",
    company: "JR East",
    category: "JR",
    area: "东京 23 区内 JR 普通列车指定范围",
    priceLabel: "购买前请确认官方价格",
    validFor: "指定日期内在适用 JR 区间使用",
    bestFor: "一天内主要坐 JR，在山手线周边移动",
    description: "适合新宿、涩谷、东京、上野、秋叶原等 JR 站点之间多次移动。",
    caution: "不覆盖地下铁和私铁，远出 23 区外需另行确认。",
    officialSearchQuery: "JR 都区内パス 公式",
    infoConfidence: "高",
    goodFor: ["JR 区间较多", "山手线周边移动", "东京 23 区内多次乘车"],
    notGoodFor: ["主要坐 Metro", "去近郊很远", "JR 和私铁混坐很多"],
    tags: ["一日券", "JR", "山手线"],
  }),
  deal({
    id: "nonbiri-holiday-suica-pass",
    name: "のんびりホリデーSuicaパス",
    company: "JR East",
    category: "JR",
    area: "东京近郊 JR 指定范围",
    priceLabel: "购买前请确认官方价格",
    validFor: "周末、节假日等指定日期和范围使用",
    bestFor: "周末短途、关东近郊一日移动",
    description: "适合假日从东京去近郊多站移动，节奏比较宽松的一天。",
    caution: "适用日期和范围有条件，平日或指定范围外不能按同样规则使用。",
    officialSearchQuery: "のんびりホリデーSuicaパス 公式",
    infoConfidence: "中",
    goodFor: ["周末短途", "关东近郊旅行", "JR 区间较多"],
    notGoodFor: ["平日出行", "只坐 1〜2 次", "私铁路线较多"],
    tags: ["JR", "观光", "近郊", "周末"],
  }),
  deal({
    id: "tokyo-free-kippu",
    name: "東京フリーきっぷ",
    company: "JR East / Tokyo Metro / 都营等",
    category: "一日券",
    area: "东京市区多家公司指定范围",
    priceLabel: "购买前请确认官方价格",
    validFor: "指定日期内在适用范围内使用",
    bestFor: "JR、Metro、都营混坐较多的一天",
    description: "适合行程复杂、跨不同铁路公司移动较多的日子。",
    caution: "价格通常比单一公司一日券高，少量移动未必划算。",
    officialSearchQuery: "東京フリーきっぷ 公式",
    infoConfidence: "高",
    goodFor: ["东京市区观光", "JR 和地下铁混坐", "一天去多个景点"],
    notGoodFor: ["只坐 1〜2 次", "主要坐单一公司路线", "去适用范围外"],
    tags: ["一日券", "JR", "Metro", "都营"],
  }),
  deal({
    id: "tokyu-line-one-day",
    name: "東急線ワンデーパス",
    company: "Tokyu",
    category: "私铁",
    area: "东急线指定范围",
    priceLabel: "购买前请确认官方价格",
    validFor: "指定日期内在适用东急线路使用",
    bestFor: "自由之丘、二子玉川、涩谷周边一日移动",
    description: "适合东京西南方向、东急沿线多站移动。",
    caution: "是否覆盖全部东急线和联络线路需以官方为准。",
    officialSearchQuery: "東急線ワンデーパス 公式",
    infoConfidence: "高",
    goodFor: ["私铁路线较多", "东急沿线散步", "东京西南方向"],
    notGoodFor: ["主要坐 JR", "主要坐地下铁", "只在一个车站附近活动"],
    tags: ["私铁", "一日券", "西南东京"],
  }),
  deal({
    id: "odakyu-one-day",
    name: "小田急一日乗車券",
    company: "Odakyu",
    category: "私铁",
    area: "小田急线指定范围",
    priceLabel: "购买前请确认官方价格",
    validFor: "指定日期内在适用小田急线路使用",
    bestFor: "新宿出发，小田急沿线多次移动",
    description: "适合一天内在小田急沿线慢慢移动，比如下北泽、登户、町田方向。",
    caution: "是否包含特急或其他交通需要单独确认。",
    officialSearchQuery: "小田急 一日乗車券 公式",
    infoConfidence: "中",
    goodFor: ["私铁路线较多", "小田急沿线散步", "周末短途"],
    notGoodFor: ["主要坐 Metro", "主要坐 JR", "只坐一次往返"],
    tags: ["私铁", "一日券", "小田急"],
  }),
  deal({
    id: "keio-inokashira-one-day",
    name: "京王線・井の頭線一日乗車券",
    company: "Keio",
    category: "私铁",
    area: "京王线、井之头线指定范围",
    priceLabel: "购买前请确认官方价格",
    validFor: "指定日期内在适用线路使用",
    bestFor: "吉祥寺、下北泽、明大前、高尾方向移动",
    description: "适合京王和井之头线沿线一天内多站移动。",
    caution: "高尾山方向或联络交通是否包含，请以官方信息为准。",
    officialSearchQuery: "京王線 井の頭線 一日乗車券 公式",
    infoConfidence: "中",
    goodFor: ["私铁路线较多", "东京西侧短途", "周末短途"],
    notGoodFor: ["主要坐 JR", "主要坐地下铁", "路线不在京王范围"],
    tags: ["私铁", "一日券", "京王"],
  }),
  deal({
    id: "seibu-one-day-free",
    name: "西武線一日フリーきっぷ",
    company: "Seibu",
    category: "私铁",
    area: "西武线指定范围",
    priceLabel: "购买前请确认官方价格",
    validFor: "指定日期内在适用西武线路使用",
    bestFor: "池袋、新宿出发去西武沿线多站移动",
    description: "适合西武沿线一日散步或短途行程。",
    caution: "不同期间票种和适用范围可能变化，购买前请确认。",
    officialSearchQuery: "西武線 一日フリーきっぷ 公式",
    infoConfidence: "中",
    goodFor: ["私铁路线较多", "周末短途", "西武沿线"],
    notGoodFor: ["主要坐 JR", "只坐 1〜2 次", "路线不在适用范围"],
    tags: ["私铁", "一日券", "西武"],
  }),
  deal({
    id: "tobu-free-kippu",
    name: "東武鉄道フリーきっぷ",
    company: "Tobu",
    category: "私铁",
    area: "东武线及观光方向指定范围",
    priceLabel: "购买前请确认官方价格",
    validFor: "根据票种在指定区域和期间使用",
    bestFor: "东武沿线、日光、鬼怒川或近郊观光",
    description: "适合从浅草、池袋等方向出发，去东武沿线或近郊观光。",
    caution: "东武票种较多，购买前请按目的地确认。",
    officialSearchQuery: "東武鉄道 フリーきっぷ 公式",
    infoConfidence: "中",
    goodFor: ["关东近郊旅行", "私铁路线较多", "周末短途"],
    notGoodFor: ["只在东京市区移动", "主要坐 Metro", "行程路线不确定"],
    tags: ["私铁", "观光", "近郊"],
  }),
  deal({
    id: "keikyu-haneda-ticket",
    name: "京急羽田空港関連きっぷ",
    company: "Keikyu",
    category: "机场交通",
    area: "羽田机场至品川、横滨方向",
    priceLabel: "购买前请确认官方价格",
    validFor: "机场交通或组合票，适用范围请确认",
    bestFor: "羽田机场进出，去品川、横滨方向",
    description: "适合羽田机场到东京南侧或横滨方向的移动。",
    caution: "不同组合票内容不同，不要只看票名就购买。",
    officialSearchQuery: "京急 羽田空港 お得なきっぷ 公式",
    infoConfidence: "中",
    goodFor: ["去机场", "羽田机场", "横滨方向"],
    notGoodFor: ["成田机场", "只在市区短程移动", "主要坐 JR"],
    tags: ["机场", "羽田", "私铁"],
  }),
  deal({
    id: "narita-access-ticket",
    name: "成田空港アクセス系きっぷ",
    company: "Keisei / JR East 等",
    category: "机场交通",
    area: "成田机场与东京市区之间",
    priceLabel: "购买前请确认官方价格",
    validFor: "机场交通票种，适用路线和购买条件请确认",
    bestFor: "成田机场进出、带行李、希望少换乘",
    description: "成田机场有多种铁路选择，适合先按住宿区域选择路线，再看优惠票。",
    caution: "Keisei、JR 等路线不同，不要把不同公司的票混用。",
    officialSearchQuery: "成田空港 アクセス お得なきっぷ 公式",
    infoConfidence: "中",
    goodFor: ["去机场", "成田机场", "带行李"],
    notGoodFor: ["羽田机场", "东京市区内短程", "不确定到达车站"],
    tags: ["机场", "成田", "JR", "私铁"],
  }),
  deal({
    id: "nex-round-trip",
    name: "Narita Express 往返优惠票",
    company: "JR East",
    category: "机场交通",
    area: "成田机场与东京市区之间",
    priceLabel: "购买前请确认官方价格",
    validFor: "机场往返交通，适用条件请确认官方信息",
    bestFor: "成田机场进出、带行李、想少换乘",
    description: "适合从成田机场到东京、新宿、涩谷等 JR 主要站点。",
    caution: "使用期限、购买资格和适用列车请以官方信息为准。",
    officialSearchQuery: "N'EX Tokyo Round Trip Ticket 公式",
    infoConfidence: "中",
    goodFor: ["去机场", "成田机场", "JR 主要车站"],
    notGoodFor: ["羽田机场", "只坐普通市区交通", "住宿靠近京成沿线"],
    tags: ["机场", "JR", "成田"],
  }),
  deal({
    id: "keisei-skyliner-discount",
    name: "Skyliner 优惠票",
    company: "Keisei",
    category: "机场交通",
    area: "成田机场至上野、日暮里方向",
    priceLabel: "购买前请确认官方价格",
    validFor: "机场特急列车，票种和购买渠道请确认",
    bestFor: "成田机场到上野、日暮里一带",
    description: "适合住在东京东侧，想从成田机场较快进城。",
    caution: "折扣票购买渠道和条件可能不同，出发前请确认。",
    officialSearchQuery: "京成スカイライナー 割引 公式",
    infoConfidence: "中",
    goodFor: ["去机场", "成田机场", "上野日暮里方向"],
    notGoodFor: ["羽田机场", "目的地在东京西侧", "不坐京成线"],
    tags: ["机场", "成田", "私铁"],
  }),
  deal({
    id: "enoden-one-day",
    name: "江ノ電一日乗車券",
    company: "Enoden",
    category: "观光",
    area: "藤泽、江之岛、镰仓方向",
    priceLabel: "购买前请确认官方价格",
    validFor: "指定日期内在江之电适用范围使用",
    bestFor: "江之岛、镰仓沿线慢慢逛",
    description: "适合一天内在江之电沿线多站下车散步。",
    caution: "从东京到藤泽或镰仓的交通通常不包含在内，请另行确认。",
    officialSearchQuery: "江ノ電 一日乗車券 のりおりくん 公式",
    infoConfidence: "高",
    goodFor: ["关东近郊旅行", "镰仓江之岛", "周末短途"],
    notGoodFor: ["只坐一次", "东京市区移动", "东京到当地交通未确认"],
    tags: ["观光", "一日券", "近郊"],
  }),
  deal({
    id: "hakone-freepass",
    name: "箱根フリーパス",
    company: "Odakyu",
    category: "观光",
    area: "新宿至箱根及箱根当地交通",
    priceLabel: "购买前请确认官方价格",
    validFor: "多日观光周游票，适用交通请确认",
    bestFor: "箱根温泉、芦之湖、两天一夜观光",
    description: "适合从东京出发去箱根，且会使用当地多种交通工具。",
    caution: "浪漫特快、指定席或追加费用请提前确认。",
    officialSearchQuery: "箱根フリーパス 公式",
    infoConfidence: "高",
    goodFor: ["关东近郊旅行", "温泉", "多日观光"],
    notGoodFor: ["只在东京市区", "当天只往返一次", "不使用当地交通"],
    tags: ["观光", "私铁", "温泉"],
  }),
  deal({
    id: "nikko-kinugawa-freepass",
    name: "日光・鬼怒川方面フリーパス",
    company: "Tobu",
    category: "观光",
    area: "浅草至日光、鬼怒川方向",
    priceLabel: "购买前请确认官方价格",
    validFor: "多日观光票，适用交通请确认",
    bestFor: "日光、鬼怒川温泉、多日观光",
    description: "适合从东京去日光方向，并在当地继续移动。",
    caution: "特急列车、座席和使用期限请以官方为准。",
    officialSearchQuery: "東武 日光 鬼怒川 フリーパス 公式",
    infoConfidence: "中",
    goodFor: ["关东近郊旅行", "温泉", "多日观光"],
    notGoodFor: ["只在市区移动", "不坐东武线", "只坐 1〜2 次"],
    tags: ["观光", "私铁", "温泉"],
  }),
  deal({
    id: "kamakura-enoshima-freepass",
    name: "鎌倉・江の島方面フリーパス",
    company: "Odakyu / Enoden 等",
    category: "观光",
    area: "镰仓、江之岛方向",
    priceLabel: "购买前请确认官方价格",
    validFor: "根据票种在指定区域和期间使用",
    bestFor: "镰仓、江之岛一日或短途观光",
    description: "适合从东京出发去海边方向，并在当地多次移动。",
    caution: "不同公司票种覆盖范围不同，先按出发站确认。",
    officialSearchQuery: "鎌倉 江の島 フリーパス 公式",
    infoConfidence: "中",
    goodFor: ["关东近郊旅行", "周末短途", "多个景点"],
    notGoodFor: ["只去一个景点", "不使用当地交通", "出发路线未确认"],
    tags: ["观光", "近郊", "私铁"],
  }),
  deal({
    id: "yokohama-minatomirai-one-day",
    name: "横浜みなとみらい系一日券",
    company: "Minatomirai Line / Yokohama Municipal 等",
    category: "观光",
    area: "横滨、港未来、中华街方向",
    priceLabel: "购买前请确认官方价格",
    validFor: "横滨相关一日票或组合票，适用范围请确认",
    bestFor: "横滨港未来、中华街、元町一带多点移动",
    description: "适合一天在横滨多个区域活动，不想每段单独考虑票价。",
    caution: "横滨票种较多，覆盖地铁、港未来线或巴士的范围可能不同。",
    officialSearchQuery: "横浜 みなとみらい 一日乗車券 公式",
    infoConfidence: "中",
    goodFor: ["关东近郊旅行", "东京市区外观光", "多个景点"],
    notGoodFor: ["只坐一次往返", "主要在东京市区", "路线不在横滨范围"],
    tags: ["观光", "近郊", "一日券"],
  }),
  deal({
    id: "rinkai-line-one-day",
    name: "りんかい線一日乗車券",
    company: "Rinkai Line",
    category: "观光",
    area: "大崎、台场、新木场方向",
    priceLabel: "购买前请确认官方价格",
    validFor: "指定日期内在临海线适用范围使用",
    bestFor: "台场、有明、湾岸区域多站移动",
    description: "适合一天内沿临海线去多个湾岸区域地点。",
    caution: "JR 直通或其他线路是否包含，请以官方说明为准。",
    officialSearchQuery: "りんかい線 一日乗車券 公式",
    infoConfidence: "中",
    goodFor: ["东京市区观光", "台场湾岸", "一天坐多次"],
    notGoodFor: ["只坐 1〜2 次", "主要坐百合海鸥号", "路线不在临海线"],
    tags: ["观光", "一日券", "台场"],
  }),
  deal({
    id: "yurikamome-one-day",
    name: "ゆりかもめ一日乗車券",
    company: "Yurikamome",
    category: "观光",
    area: "新桥、丰洲、台场方向",
    priceLabel: "购买前请确认官方价格",
    validFor: "指定日期内在百合海鸥号适用范围使用",
    bestFor: "台场、丰洲、有明一带多站移动",
    description: "适合一天在湾岸区域慢慢逛，不想每次单独刷卡。",
    caution: "如果只坐一两次，普通 IC 卡通常更简单。",
    officialSearchQuery: "ゆりかもめ 一日乗車券 公式",
    infoConfidence: "高",
    goodFor: ["东京市区观光", "台场湾岸", "一天坐多次"],
    notGoodFor: ["只坐 1〜2 次", "主要坐 JR", "不去湾岸区域"],
    tags: ["观光", "一日券", "台场"],
  }),
  deal({
    id: "tokyo-sakura-tram-pass",
    name: "東京さくらトラム一日乗車券",
    company: "東京都交通局",
    category: "观光",
    area: "东京 Sakura Tram 沿线",
    priceLabel: "购买前请确认官方价格",
    validFor: "指定日期内在适用线路使用",
    bestFor: "早稻田、鬼子母神、庚申塚等慢节奏散步",
    description: "适合想体验东京路面电车，沿线慢慢逛的一天。",
    caution: "适用范围较窄，出行前请确认是否符合当天路线。",
    officialSearchQuery: "東京さくらトラム 一日乗車券 公式",
    infoConfidence: "高",
    goodFor: ["东京市区观光", "慢旅行", "一天坐多次"],
    notGoodFor: ["赶时间", "主要坐 JR", "路线不在沿线"],
    tags: ["观光", "都营", "慢旅行"],
  }),
  deal({
    id: "jr-tokyo-wide-pass",
    name: "JR Tokyo Wide Pass",
    company: "JR East",
    category: "观光",
    area: "东京近郊及部分关东观光区域",
    priceLabel: "价格和条件可能变化，请以官方信息为准",
    validFor: "多日型观光票，适用范围请看官方说明",
    bestFor: "东京近郊远出、温泉、滑雪或多日观光",
    description: "适合从东京出发去近郊多地，不适合只在市区短程移动。",
    caution: "购买资格、指定席规则和可搭乘列车需要提前确认。",
    officialSearchQuery: "JR Tokyo Wide Pass official",
    infoConfidence: "中",
    goodFor: ["关东近郊旅行", "多日观光", "JR 区间较多"],
    notGoodFor: ["只在东京市区", "只坐 1〜2 次", "不坐 JR"],
    tags: ["观光", "JR", "近郊"],
  }),
  deal({
    id: "seishun-18-ticket",
    name: "青春18きっぷ",
    company: "JR Group",
    category: "JR",
    area: "JR 普通列车等，按季节和规则使用",
    priceLabel: "季节性票价，请以官方信息为准",
    validFor: "通常为季节限定，具体规则每期确认",
    bestFor: "时间充裕、长距离普通列车旅行",
    description: "适合慢旅行和多日低成本移动，不适合赶时间。",
    caution: "发售期间、使用期间和可搭乘列车限制较多。",
    officialSearchQuery: "青春18きっぷ 公式",
    infoConfidence: "低",
    lastCheckedLabel: "期间限定，需购买前确认",
    goodFor: ["周末短途", "长距离慢旅行", "JR 普通列车"],
    notGoodFor: ["赶时间", "新干线或特急为主", "不想研究规则"],
    tags: ["JR", "观光", "长距离"],
  }),
  deal({
    id: "jr-commuter-pass",
    name: "JR 通勤定期券",
    company: "JR East",
    category: "学生 / 通勤",
    area: "JR 固定区间",
    priceLabel: "按区间计算，请以官方信息为准",
    validFor: "1 个月、3 个月、6 个月等常见期间",
    bestFor: "固定 JR 区间通勤、通学",
    description: "适合每天走同一 JR 路线的人，购买前可先估算月内乘车次数。",
    caution: "跨公司联络定期需要确认可购买范围。",
    officialSearchQuery: "JR東日本 定期券 通勤 通学 公式",
    infoConfidence: "高",
    goodFor: ["JR 区间较多", "固定通勤", "固定通学"],
    notGoodFor: ["主要坐 Metro", "路线不固定", "偶尔乘车"],
    tags: ["JR", "定期券", "通勤"],
  }),
  deal({
    id: "tokyo-metro-commuter-pass",
    name: "東京メトロ定期券",
    company: "Tokyo Metro",
    category: "学生 / 通勤",
    area: "东京 Metro 固定区间",
    priceLabel: "按区间计算，请以官方信息为准",
    validFor: "固定区间、固定期间",
    bestFor: "每天主要坐 Metro 通勤或上学",
    description: "适合固定 Metro 区间移动，也可以确认是否能与其他公司联络定期组合。",
    caution: "购买条件、联络范围和学生证明请以官方为准。",
    officialSearchQuery: "東京メトロ 定期券 通勤 通学 公式",
    infoConfidence: "高",
    goodFor: ["Metro 路线较多", "固定通勤", "固定通学"],
    notGoodFor: ["主要坐 JR", "路线每天不同", "短期观光"],
    tags: ["Metro", "定期券", "学生"],
  }),
  deal({
    id: "toei-commuter-pass",
    name: "都営地下鉄定期券",
    company: "東京都交通局",
    category: "学生 / 通勤",
    area: "都营地下铁固定区间",
    priceLabel: "按区间计算，请以官方信息为准",
    validFor: "固定区间、固定期间",
    bestFor: "每天主要坐都营地下铁通勤或上学",
    description: "适合都营地下铁固定区间移动，尤其是线路长期稳定的人。",
    caution: "学生、联络定期和购买地点请以官方为准。",
    officialSearchQuery: "都営地下鉄 定期券 通勤 通学 公式",
    infoConfidence: "高",
    goodFor: ["都营地下铁较多", "固定通勤", "固定通学"],
    notGoodFor: ["主要坐 Metro", "路线每天不同", "短期观光"],
    tags: ["都营", "定期券", "学生"],
  }),
  deal({
    id: "ic-card-normal",
    name: "普通 IC 卡乘车",
    company: "各铁路公司",
    category: "一日券",
    area: "首都圈多数交通",
    priceLabel: "按实际乘车扣费",
    validFor: "日常单次或少量乘车",
    bestFor: "今天只坐 1〜2 次，路线不确定",
    description: "很多日常场景下，普通 IC 卡最简单，不需要为了省一点点而买错票。",
    caution: "如果一天内多次进出站，再考虑一日券或周游票。",
    officialSearchQuery: "Suica PASMO 使い方 公式",
    infoConfidence: "高",
    lastCheckedLabel: "常见日常方式，仍需确认使用范围",
    goodFor: ["只坐 1〜2 次", "路线不确定", "日常移动"],
    notGoodFor: ["一天坐很多次", "固定通勤可考虑定期", "明确多景点观光"],
    tags: ["IC 卡", "日常", "省心"],
  }),
];
