import type { PlayDestination, PlayFilterTag, PlayMode, PlayPlanStep } from "@/lib/play/types";

const images = {
  cafe: "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1200&q=80",
  city: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1200&q=80",
  coast: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
  garden: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
  night: "https://images.unsplash.com/photo-1505069446780-4ef442b5207f?auto=format&fit=crop&w=1200&q=80",
  old: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
  shopping: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
  woods: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
};

const defaultSteps: PlayPlanStep[] = [
  { timeLabel: "13:00", title: "从车站出发", description: "先不用急着找店，慢慢走到主要街区。", estimatedDuration: "20分钟" },
  { timeLabel: "14:00", title: "找一家店或公园休息", description: "坐下来看看今天想继续逛哪里。", estimatedDuration: "45分钟" },
  { timeLabel: "15:30", title: "去附近景点或商店街", description: "半日游刚好，不需要把行程排得太满。", estimatedDuration: "60〜90分钟" },
];

type Seed = Omit<PlayDestination, "afternoonPlan" | "budgetBreakdown" | "eveningPlan" | "image" | "morningPlan" | "planSteps" | "rainyPlan" | "tags" | "transportNote"> & {
  imageKey: keyof typeof images;
  tags: PlayFilterTag[];
  afternoonPlan?: string;
  budgetBreakdown?: string[];
  eveningPlan?: string;
  morningPlan?: string;
  planSteps?: PlayPlanStep[];
  rainyPlan?: string;
  transportNote?: string;
};

function destination(seed: Seed): PlayDestination {
  const tags = enrichTags(seed);
  return {
    ...seed,
    image: images[seed.imageKey],
    tags,
    planSteps: seed.planSteps ?? defaultSteps,
    morningPlan: seed.morningPlan ?? `${seed.name}适合先从车站周边开始，不用急着赶景点。`,
    afternoonPlan: seed.afternoonPlan ?? seed.reason,
    eveningPlan: seed.eveningPlan ?? "如果还有体力，可以在车站附近吃饭后回家。",
    rainyPlan: seed.rainyPlan ?? "下雨时减少户外时间，多安排咖啡店、商店街或室内休息点。",
    budgetBreakdown: seed.budgetBreakdown ?? ["交通：按出发地不同", "咖啡或小吃：500〜1200円", "吃饭：1000〜2500円"],
    transportNote: seed.transportNote ?? `${seed.area}位于${seed.prefecture}，出发前建议确认换乘和回程时间。`,
  };
}

export const playModes: PlayMode[] = ["半日游", "一日游", "傍晚出发", "周末小旅行"];
export const playTimeTags: PlayFilterTag[] = ["半日", "一日", "傍晚出发", "周末"];
export const playCompanionTags: PlayFilterTag[] = ["一个人", "朋友", "情侣", "家人"];
export const playTypeTags: PlayFilterTag[] = ["自然", "咖啡", "购物", "老街", "海边", "夜景", "不想太累", "想有出门感", "低预算", "雨天也可以", "想拍照", "想吃点好的"];

const outingIds = new Set(["kamakura", "enoshima", "yokohama", "kawagoe", "takao", "okutama", "hakone"]);
const photoIds = new Set(["nakameguro", "daikanyama", "yokohama", "enoshima", "asakusa", "odaiba", "kamakura"]);
const foodIds = new Set(["yokohama", "tsukishima", "jiyugaoka", "kichijoji", "kagurazaka", "nakameguro"]);

function enrichTags(seed: Seed): PlayFilterTag[] {
  const tags = [...seed.tags];
  if (seed.difficulty === "轻松") tags.push("不想太累");
  if (outingIds.has(seed.id) || seed.bestTime.includes("一日")) tags.push("想有出门感");
  if (photoIds.has(seed.id) || seed.tags.includes("夜景") || seed.tags.includes("海边")) tags.push("想拍照");
  if (foodIds.has(seed.id) || seed.tags.includes("咖啡")) tags.push("想吃点好的");
  return Array.from(new Set(tags));
}

export const playDestinations: PlayDestination[] = [
  destination({
    id: "kichijoji",
    name: "吉祥寺",
    japaneseName: "吉祥寺",
    englishName: "Kichijoji",
    area: "武藏野",
    prefecture: "东京",
    latitude: 35.7031,
    longitude: 139.5797,
    title: "公园、小店和咖啡都刚好",
    subtitle: "半日也不会空，一日也不会太累。",
    tags: ["半日", "周末", "一个人", "朋友", "情侣", "咖啡", "购物", "低预算", "雨天也可以"],
    bestFor: ["一个人", "朋友", "情侣"],
    bestTime: ["半日", "周末"],
    duration: "半日〜一日",
    budget: "¥1,000〜4,000",
    difficulty: "轻松",
    reason: "今天适合去吉祥寺。先去井之头公园走走，再找一家咖啡店休息。",
    tips: "周末人会多，先从公园或小路开始会比较舒服。",
    caution: "热门咖啡店可能需要排队，不想等的话可以往小巷里走。",
    imageKey: "cafe",
  }),
  destination({
    id: "inokashira-park",
    name: "井の頭公園",
    japaneseName: "井の頭恩賜公園",
    englishName: "Inokashira Park",
    area: "吉祥寺",
    prefecture: "东京",
    latitude: 35.7003,
    longitude: 139.5742,
    title: "想放松时去有水和树的地方",
    subtitle: "适合不想安排太多的半日。",
    tags: ["半日", "周末", "一个人", "情侣", "家人", "自然", "低预算"],
    bestFor: ["一个人", "情侣", "家人"],
    bestTime: ["半日", "周末"],
    duration: "2〜4 小时",
    budget: "¥0〜2,000",
    difficulty: "轻松",
    reason: "如果不想跑太远，井之头公园适合慢慢走，再回吉祥寺吃点东西。",
    tips: "天气好时适合带饮料坐一会儿，不用赶路线。",
    caution: "雨天路面可能湿滑，建议穿好走的鞋。",
    imageKey: "garden",
  }),
  destination({
    id: "kamakura",
    name: "鎌倉",
    japaneseName: "鎌倉",
    englishName: "Kamakura",
    area: "湘南",
    prefecture: "神奈川",
    latitude: 35.3192,
    longitude: 139.5467,
    title: "想有一日游感觉时，镰仓很稳",
    subtitle: "寺社、老街、海边都能组合。",
    tags: ["一日", "周末", "朋友", "情侣", "家人", "老街", "海边", "自然"],
    bestFor: ["朋友", "情侣", "家人"],
    bestTime: ["一日", "周末"],
    duration: "一日",
    budget: "¥3,000〜7,000",
    difficulty: "普通",
    reason: "想要一日游的话，鎌倉会比市区更有出门感，但不需要安排得很满。",
    tips: "可以只选小町通、鹤冈八幡宫和一个海边点，行程更轻松。",
    caution: "周末热门区域人多，回程时间建议留一点余量。",
    imageKey: "old",
  }),
  destination({
    id: "enoshima",
    name: "江ノ島",
    japaneseName: "江の島",
    englishName: "Enoshima",
    area: "湘南",
    prefecture: "神奈川",
    latitude: 35.3003,
    longitude: 139.4802,
    title: "想看海时去江之岛",
    subtitle: "比市区更像休息日。",
    tags: ["一日", "周末", "朋友", "情侣", "家人", "海边", "自然", "夜景"],
    bestFor: ["朋友", "情侣", "家人"],
    bestTime: ["一日", "周末", "傍晚出发"],
    duration: "半日〜一日",
    budget: "¥3,000〜8,000",
    difficulty: "普通",
    reason: "江ノ島适合想看海、想走一点路，又不想做太复杂计划的日子。",
    tips: "傍晚去会比较有出门感，天气好时可以看夕阳。",
    caution: "岛上上下坡比较多，脚累时不要硬走完整圈。",
    imageKey: "coast",
  }),
  destination({
    id: "yokohama",
    name: "横浜",
    japaneseName: "横浜",
    englishName: "Yokohama",
    area: "港未来",
    prefecture: "神奈川",
    latitude: 35.4437,
    longitude: 139.638,
    title: "海风、夜景和不太紧张的一日",
    subtitle: "朋友、情侣、家人都好安排。",
    tags: ["半日", "一日", "傍晚出发", "周末", "朋友", "情侣", "家人", "购物", "海边", "夜景", "雨天也可以"],
    bestFor: ["朋友", "情侣", "家人"],
    bestTime: ["半日", "一日", "傍晚出发"],
    duration: "半日〜一日",
    budget: "¥2,000〜7,000",
    difficulty: "轻松",
    reason: "横浜适合下午出发，逛港未来和海边，晚上看一点夜景。",
    tips: "雨天可以多安排商场和室内休息点。",
    caution: "范围很大，第一次去不要把港未来、中华街、山下公园都排满。",
    imageKey: "night",
  }),
  destination({
    id: "kawagoe",
    name: "川越",
    japaneseName: "川越",
    englishName: "Kawagoe",
    area: "川越",
    prefecture: "埼玉",
    latitude: 35.9251,
    longitude: 139.4858,
    title: "想走老街但不想太远",
    subtitle: "一日小旅行的距离刚好。",
    tags: ["一日", "周末", "朋友", "情侣", "家人", "老街", "低预算"],
    bestFor: ["朋友", "情侣", "家人"],
    bestTime: ["一日", "周末"],
    duration: "一日",
    budget: "¥2,000〜6,000",
    difficulty: "普通",
    reason: "川越适合想要老街感的一日游，吃点小吃、看看仓造街道就很完整。",
    tips: "可以早一点出发，中午前后到主街会比较顺。",
    caution: "热门街道周末较拥挤，别把每家店都排进行程。",
    imageKey: "old",
  }),
  destination({
    id: "takao",
    name: "高尾山",
    japaneseName: "高尾山",
    englishName: "Mount Takao",
    area: "八王子",
    prefecture: "东京",
    latitude: 35.6251,
    longitude: 139.2437,
    title: "想动一动但不想太硬核",
    subtitle: "东京近郊的轻登山选择。",
    tags: ["一日", "周末", "朋友", "情侣", "家人", "自然", "低预算"],
    bestFor: ["朋友", "情侣", "家人"],
    bestTime: ["一日", "周末"],
    duration: "一日",
    budget: "¥2,000〜5,000",
    difficulty: "稍微累",
    reason: "高尾山适合想离开市区、但不想做太重装备的一日出门。",
    tips: "体力一般的话可以使用缆车，把重点放在风景和休息。",
    caution: "雨天或鞋子不合适时不要勉强走山路。",
    imageKey: "woods",
  }),
  destination({
    id: "okutama",
    name: "奥多摩",
    japaneseName: "奥多摩",
    englishName: "Okutama",
    area: "西多摩",
    prefecture: "东京",
    latitude: 35.8095,
    longitude: 139.0965,
    title: "想真正离开城市一点",
    subtitle: "适合一整天留给自然。",
    tags: ["一日", "周末", "朋友", "情侣", "自然", "低预算"],
    bestFor: ["朋友", "情侣"],
    bestTime: ["一日", "周末"],
    duration: "一日",
    budget: "¥3,000〜7,000",
    difficulty: "稍微累",
    reason: "奥多摩适合想看山和水、愿意花一整天慢慢走的人。",
    tips: "提前确认回程车次，别把最后一班车想得太宽松。",
    caution: "天气变化和交通间隔需要留意，不适合临时很晚出发。",
    imageKey: "woods",
  }),
  destination({
    id: "yanesen",
    name: "谷根千",
    japaneseName: "谷中・根津・千駄木",
    englishName: "Yanesen",
    area: "台东 / 文京",
    prefecture: "东京",
    latitude: 35.7241,
    longitude: 139.7636,
    title: "老街和小店的半日慢逛",
    subtitle: "一个人也不会尴尬。",
    tags: ["半日", "周末", "一个人", "朋友", "老街", "咖啡", "低预算", "雨天也可以"],
    bestFor: ["一个人", "朋友"],
    bestTime: ["半日", "周末"],
    duration: "半日",
    budget: "¥1,000〜4,000",
    difficulty: "轻松",
    reason: "谷根千适合慢慢走老街，途中找咖啡店或小吃停一下。",
    tips: "不需要查太多点，沿着谷中银座附近散开走就好。",
    caution: "小店营业日不固定，遇到关门就换一家，不要太执着。",
    imageKey: "old",
  }),
  destination({
    id: "asakusa",
    name: "浅草",
    japaneseName: "浅草",
    englishName: "Asakusa",
    area: "台东",
    prefecture: "东京",
    latitude: 35.7148,
    longitude: 139.7967,
    title: "经典但不难安排",
    subtitle: "适合朋友或家人来东京时。",
    tags: ["半日", "一日", "周末", "朋友", "家人", "老街", "购物", "低预算", "雨天也可以"],
    bestFor: ["朋友", "家人"],
    bestTime: ["半日", "一日"],
    duration: "半日〜一日",
    budget: "¥1,500〜5,000",
    difficulty: "轻松",
    reason: "浅草适合想要一点东京经典感，又不想安排太复杂路线的日子。",
    tips: "可以把浅草和藏前或晴空塔方向组合，但别走太赶。",
    caution: "仲见世一带人多，带家人时注意集合点。",
    imageKey: "old",
  }),
  destination({
    id: "odaiba",
    name: "お台場",
    japaneseName: "お台場",
    englishName: "Odaiba",
    area: "湾岸",
    prefecture: "东京",
    latitude: 35.6267,
    longitude: 139.7755,
    title: "海边、商场和夜景都在一起",
    subtitle: "雨天也有室内备选。",
    tags: ["半日", "傍晚出发", "周末", "朋友", "情侣", "家人", "购物", "海边", "夜景", "雨天也可以"],
    bestFor: ["朋友", "情侣", "家人"],
    bestTime: ["半日", "傍晚出发", "周末"],
    duration: "半日〜一日",
    budget: "¥2,000〜7,000",
    difficulty: "轻松",
    reason: "お台場适合傍晚出发，看海边和灯光，天气不好也能进商场。",
    tips: "晚上看彩虹桥方向会更有出门感。",
    caution: "设施之间距离比想象中远，别把所有商场都排进去。",
    imageKey: "night",
  }),
  destination({
    id: "shimokitazawa",
    name: "下北沢",
    japaneseName: "下北沢",
    englishName: "Shimokitazawa",
    area: "世田谷",
    prefecture: "东京",
    latitude: 35.6615,
    longitude: 139.6661,
    title: "古着、咖啡和小剧场的半日",
    subtitle: "朋友或一个人都适合。",
    tags: ["半日", "周末", "一个人", "朋友", "咖啡", "购物", "低预算", "雨天也可以"],
    bestFor: ["一个人", "朋友"],
    bestTime: ["半日", "周末"],
    duration: "半日",
    budget: "¥1,500〜5,000",
    difficulty: "轻松",
    reason: "下北沢适合没有明确目的地时随便逛，古着店和咖啡店很多。",
    tips: "从车站周边往小路走，比只逛主街更有意思。",
    caution: "店很多但空间不大，周末下午会比较挤。",
    imageKey: "shopping",
  }),
  destination({
    id: "kagurazaka",
    name: "神楽坂",
    japaneseName: "神楽坂",
    englishName: "Kagurazaka",
    area: "新宿",
    prefecture: "东京",
    latitude: 35.7039,
    longitude: 139.7355,
    title: "小巷、甜点和安静晚饭",
    subtitle: "适合傍晚慢慢走。",
    tags: ["半日", "傍晚出发", "一个人", "情侣", "咖啡", "老街", "雨天也可以"],
    bestFor: ["一个人", "情侣"],
    bestTime: ["半日", "傍晚出发"],
    duration: "2〜4 小时",
    budget: "¥1,500〜6,000",
    difficulty: "轻松",
    reason: "神楽坂适合傍晚出发，走小巷、吃甜点或找一家安静的店。",
    tips: "下雨天也可以把重点放在甜点和室内小店。",
    caution: "坡道较多，穿舒服的鞋会更好。",
    imageKey: "cafe",
  }),
  destination({
    id: "kiyosumi-shirakawa",
    name: "清澄白河",
    japaneseName: "清澄白河",
    englishName: "Kiyosumi-shirakawa",
    area: "江东",
    prefecture: "东京",
    latitude: 35.6829,
    longitude: 139.7988,
    title: "咖啡和庭园的半日",
    subtitle: "一个人慢慢逛很舒服。",
    tags: ["半日", "一个人", "朋友", "情侣", "咖啡", "自然", "低预算", "雨天也可以"],
    bestFor: ["一个人", "朋友", "情侣"],
    bestTime: ["半日"],
    duration: "半日",
    budget: "¥1,000〜4,000",
    difficulty: "轻松",
    reason: "如果不想跑太远，清澄白河适合半日慢慢逛，咖啡和庭园刚好平衡。",
    tips: "可以先咖啡，再去庭园或河边散步。",
    caution: "热门咖啡店可能排队，备选店多准备一两家会轻松。",
    imageKey: "cafe",
  }),
  destination({
    id: "kuramae",
    name: "蔵前",
    japaneseName: "蔵前",
    englishName: "Kuramae",
    area: "台东",
    prefecture: "东京",
    latitude: 35.7042,
    longitude: 139.7908,
    title: "手作小店和咖啡的半日",
    subtitle: "适合下雨天也想出门一点。",
    tags: ["半日", "一个人", "朋友", "情侣", "咖啡", "购物", "雨天也可以"],
    bestFor: ["一个人", "朋友", "情侣"],
    bestTime: ["半日"],
    duration: "半日",
    budget: "¥1,500〜5,000",
    difficulty: "轻松",
    reason: "蔵前适合逛小店和咖啡，天气普通也不影响太多。",
    tips: "可以和浅草组合，但半日的话只选一边会更轻松。",
    caution: "很多小店空间较小，带大件行李会不方便。",
    imageKey: "cafe",
  }),
  destination({
    id: "nakameguro",
    name: "中目黒",
    japaneseName: "中目黒",
    englishName: "Nakameguro",
    area: "目黑",
    prefecture: "东京",
    latitude: 35.6443,
    longitude: 139.6992,
    title: "河边、咖啡和轻松晚餐",
    subtitle: "情侣或朋友都自然。",
    tags: ["半日", "傍晚出发", "朋友", "情侣", "咖啡", "购物", "夜景", "雨天也可以"],
    bestFor: ["朋友", "情侣"],
    bestTime: ["半日", "傍晚出发"],
    duration: "半日",
    budget: "¥2,000〜6,000",
    difficulty: "轻松",
    reason: "中目黒适合下午或傍晚出发，沿河走走，再找店吃饭。",
    tips: "不用只盯着樱花季，普通周末也适合慢逛。",
    caution: "热门季节人很多，建议避开最挤的时间。",
    imageKey: "city",
  }),
  destination({
    id: "daikanyama",
    name: "代官山",
    japaneseName: "代官山",
    englishName: "Daikanyama",
    area: "涩谷",
    prefecture: "东京",
    latitude: 35.6481,
    longitude: 139.7037,
    title: "书店、咖啡和安静小路",
    subtitle: "适合半日小小换气。",
    tags: ["半日", "一个人", "情侣", "咖啡", "购物", "雨天也可以"],
    bestFor: ["一个人", "情侣"],
    bestTime: ["半日"],
    duration: "半日",
    budget: "¥1,500〜6,000",
    difficulty: "轻松",
    reason: "代官山适合想安静一点逛书店和咖啡店的半日。",
    tips: "可以和中目黑或惠比寿组合，但别排太满。",
    caution: "消费选择差异较大，低预算时先设好上限。",
    imageKey: "cafe",
  }),
  destination({
    id: "jiyugaoka",
    name: "自由が丘",
    japaneseName: "自由が丘",
    englishName: "Jiyugaoka",
    area: "目黑",
    prefecture: "东京",
    latitude: 35.6074,
    longitude: 139.6687,
    title: "甜点、小店和轻松聊天",
    subtitle: "适合情侣或朋友的半日。",
    tags: ["半日", "周末", "朋友", "情侣", "咖啡", "购物", "雨天也可以"],
    bestFor: ["朋友", "情侣"],
    bestTime: ["半日", "周末"],
    duration: "半日",
    budget: "¥1,500〜6,000",
    difficulty: "轻松",
    reason: "自由が丘适合想吃甜点、逛小店，又不想太累的日子。",
    tips: "先找休息点，再慢慢逛周边小路。",
    caution: "热门甜点店排队时，换一家也不会太影响体验。",
    imageKey: "cafe",
  }),
  destination({
    id: "futakotamagawa",
    name: "二子玉川",
    japaneseName: "二子玉川",
    englishName: "Futako-tamagawa",
    area: "世田谷",
    prefecture: "东京",
    latitude: 35.6115,
    longitude: 139.6265,
    title: "河边和商场之间切换",
    subtitle: "家人、朋友都好安排。",
    tags: ["半日", "周末", "朋友", "情侣", "家人", "自然", "购物", "低预算", "雨天也可以"],
    bestFor: ["朋友", "情侣", "家人"],
    bestTime: ["半日", "周末"],
    duration: "半日",
    budget: "¥1,000〜6,000",
    difficulty: "轻松",
    reason: "二子玉川适合天气好时去河边，天气一般时进商场。",
    tips: "带家人时路线简单，休息点也多。",
    caution: "河边风大时注意保暖，别把户外时间安排太长。",
    imageKey: "garden",
  }),
  destination({
    id: "tachikawa",
    name: "立川",
    japaneseName: "立川",
    englishName: "Tachikawa",
    area: "多摩",
    prefecture: "东京",
    latitude: 35.6984,
    longitude: 139.4136,
    title: "购物、吃饭和公园的组合",
    subtitle: "适合不想进市中心的人。",
    tags: ["半日", "一日", "周末", "朋友", "家人", "购物", "自然", "雨天也可以"],
    bestFor: ["朋友", "家人"],
    bestTime: ["半日", "一日", "周末"],
    duration: "半日〜一日",
    budget: "¥1,500〜6,000",
    difficulty: "轻松",
    reason: "立川适合西东京方向的半日或一日，不用跑到市中心也能玩得完整。",
    tips: "天气好就加公园，天气不好就以商场和吃饭为主。",
    caution: "站周边范围大，约人时把集合点说清楚。",
    imageKey: "shopping",
  }),
  destination({
    id: "showa-kinen-park",
    name: "昭和記念公園",
    japaneseName: "国営昭和記念公園",
    englishName: "Showa Kinen Park",
    area: "立川",
    prefecture: "东京",
    latitude: 35.7044,
    longitude: 139.3946,
    title: "想在大公园待一整段时间",
    subtitle: "家人或朋友都适合。",
    tags: ["半日", "一日", "周末", "朋友", "情侣", "家人", "自然", "低预算"],
    bestFor: ["朋友", "情侣", "家人"],
    bestTime: ["半日", "一日", "周末"],
    duration: "半日〜一日",
    budget: "¥1,000〜4,000",
    difficulty: "普通",
    reason: "昭和纪念公园适合想把半天交给自然和大空间的日子。",
    tips: "可以带点饮料和简单食物，节奏会更舒服。",
    caution: "园区很大，不要试图一次走完所有区域。",
    imageKey: "garden",
  }),
  destination({
    id: "toyosu",
    name: "豊洲",
    japaneseName: "豊洲",
    englishName: "Toyosu",
    area: "湾岸",
    prefecture: "东京",
    latitude: 35.6549,
    longitude: 139.7967,
    title: "海边、市场和商场的轻松组合",
    subtitle: "雨天也有备选。",
    tags: ["半日", "周末", "朋友", "情侣", "家人", "购物", "海边", "雨天也可以"],
    bestFor: ["朋友", "情侣", "家人"],
    bestTime: ["半日", "周末"],
    duration: "半日",
    budget: "¥1,500〜6,000",
    difficulty: "轻松",
    reason: "豊洲适合想看一点海边，又希望有商场休息点的日子。",
    tips: "饭点人多，先走海边再吃饭也可以。",
    caution: "市场和设施营业时间可能不同，出发前简单确认一下。",
    imageKey: "city",
  }),
  destination({
    id: "tsukishima",
    name: "月島",
    japaneseName: "月島",
    englishName: "Tsukishima",
    area: "中央",
    prefecture: "东京",
    latitude: 35.6647,
    longitude: 139.7847,
    title: "老街、文字烧和河边夜风",
    subtitle: "傍晚出发也刚好。",
    tags: ["半日", "傍晚出发", "朋友", "情侣", "老街", "夜景", "低预算", "雨天也可以"],
    bestFor: ["朋友", "情侣"],
    bestTime: ["半日", "傍晚出发"],
    duration: "2〜4 小时",
    budget: "¥1,500〜5,000",
    difficulty: "轻松",
    reason: "月島适合傍晚出发，吃点东西，再沿河边走一小段。",
    tips: "不想排队的话避开最热门饭点。",
    caution: "餐厅选择多但风格相近，先看预算再决定。",
    imageKey: "old",
  }),
  destination({
    id: "shibamata",
    name: "柴又",
    japaneseName: "柴又",
    englishName: "Shibamata",
    area: "葛饰",
    prefecture: "东京",
    latitude: 35.7563,
    longitude: 139.8754,
    title: "东京东侧的老街半日",
    subtitle: "节奏很慢，适合换换空气。",
    tags: ["半日", "周末", "一个人", "家人", "老街", "低预算"],
    bestFor: ["一个人", "家人"],
    bestTime: ["半日", "周末"],
    duration: "半日",
    budget: "¥1,000〜4,000",
    difficulty: "轻松",
    reason: "柴又适合想看老街和日常感，又不想跑出很远的半日。",
    tips: "可以把参道和江户川边组合起来。",
    caution: "店铺关门较早时，太晚出发可能会少一些选择。",
    imageKey: "old",
  }),
  destination({
    id: "sugamo",
    name: "巣鴨",
    japaneseName: "巣鴨",
    englishName: "Sugamo",
    area: "丰岛",
    prefecture: "东京",
    latitude: 35.7335,
    longitude: 139.7394,
    title: "商店街和生活感的一下午",
    subtitle: "低预算也能慢慢逛。",
    tags: ["半日", "一个人", "家人", "老街", "购物", "低预算", "雨天也可以"],
    bestFor: ["一个人", "家人"],
    bestTime: ["半日"],
    duration: "半日",
    budget: "¥500〜3,000",
    difficulty: "轻松",
    reason: "巣鴨适合想看生活感和商店街的日子，不用做复杂攻略。",
    tips: "可以边走边买点小吃，不需要安排太多点。",
    caution: "部分店铺偏早关门，傍晚后选择会少一些。",
    imageKey: "shopping",
  }),
  destination({
    id: "koenji",
    name: "高円寺",
    japaneseName: "高円寺",
    englishName: "Koenji",
    area: "杉并",
    prefecture: "东京",
    latitude: 35.7055,
    longitude: 139.6497,
    title: "古着、音乐和小店的一下午",
    subtitle: "一个人或朋友都自然。",
    tags: ["半日", "周末", "一个人", "朋友", "购物", "咖啡", "低预算", "雨天也可以"],
    bestFor: ["一个人", "朋友"],
    bestTime: ["半日", "周末"],
    duration: "半日",
    budget: "¥1,000〜5,000",
    difficulty: "轻松",
    reason: "高円寺适合随便逛古着、小店和咖啡，不需要把路线安排得很满。",
    tips: "可以先逛商店街，再往小路找咖啡。",
    caution: "古着店很多，容易越逛越久，先留回程时间。",
    imageKey: "shopping",
  }),
  destination({
    id: "nakano",
    name: "中野",
    japaneseName: "中野",
    englishName: "Nakano",
    area: "中野",
    prefecture: "东京",
    latitude: 35.706,
    longitude: 139.6657,
    title: "商店街、二手小店和便宜吃饭",
    subtitle: "半日低预算很合适。",
    tags: ["半日", "一个人", "朋友", "购物", "低预算", "雨天也可以"],
    bestFor: ["一个人", "朋友"],
    bestTime: ["半日"],
    duration: "半日",
    budget: "¥1,000〜4,000",
    difficulty: "轻松",
    reason: "中野适合低预算半日，商店街、二手小店和吃饭点都集中。",
    tips: "下雨天也能在商店街和室内区域慢慢逛。",
    caution: "室内通道有时人多，约人时定清楚集合点。",
    imageKey: "shopping",
  }),
  destination({
    id: "ikebukuro",
    name: "池袋",
    japaneseName: "池袋",
    englishName: "Ikebukuro",
    area: "丰岛",
    prefecture: "东京",
    latitude: 35.7295,
    longitude: 139.7109,
    title: "购物、室内和吃饭都方便",
    subtitle: "雨天也比较稳。",
    tags: ["半日", "傍晚出发", "朋友", "家人", "购物", "低预算", "雨天也可以"],
    bestFor: ["朋友", "家人"],
    bestTime: ["半日", "傍晚出发"],
    duration: "半日",
    budget: "¥1,500〜6,000",
    difficulty: "轻松",
    reason: "池袋适合天气不确定时，室内选择多，吃饭和购物都方便。",
    tips: "可以先决定东口或西口，不然容易走散。",
    caution: "站内和地下通道复杂，第一次约人要说清出口。",
    imageKey: "city",
  }),
  destination({
    id: "shinjuku-gyoen",
    name: "新宿御苑",
    japaneseName: "新宿御苑",
    englishName: "Shinjuku Gyoen",
    area: "新宿",
    prefecture: "东京",
    latitude: 35.6852,
    longitude: 139.7101,
    title: "市中心里的大公园半日",
    subtitle: "想安静一点时很适合。",
    tags: ["半日", "周末", "一个人", "情侣", "家人", "自然", "低预算"],
    bestFor: ["一个人", "情侣", "家人"],
    bestTime: ["半日", "周末"],
    duration: "2〜4 小时",
    budget: "¥500〜3,000",
    difficulty: "轻松",
    reason: "新宿御苑适合想在市中心放松，又不想走太远的半日。",
    tips: "可以带饮料坐一会儿，之后再去新宿吃饭。",
    caution: "开放时间和入园规则可能变化，出发前简单确认。",
    imageKey: "garden",
  }),
  destination({
    id: "yoyogi-park",
    name: "代々木公園",
    japaneseName: "代々木公園",
    englishName: "Yoyogi Park",
    area: "涩谷 / 原宿",
    prefecture: "东京",
    latitude: 35.6717,
    longitude: 139.6949,
    title: "公园、原宿和轻松聊天",
    subtitle: "低预算也有周末感。",
    tags: ["半日", "周末", "朋友", "情侣", "家人", "自然", "购物", "低预算"],
    bestFor: ["朋友", "情侣", "家人"],
    bestTime: ["半日", "周末"],
    duration: "半日",
    budget: "¥500〜4,000",
    difficulty: "轻松",
    reason: "代代木公园适合低预算半日，走走公园，再去原宿或涩谷吃点东西。",
    tips: "天气好时先公园，累了再转去附近室内。",
    caution: "活动日人会多，想安静就往公园深处走。",
    imageKey: "garden",
  }),
];
