import type { FoodMoodTag, FoodRecommendation } from "@/lib/food/types";

const image = "https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?auto=format&fit=crop&w=1200&q=80";

export const foodCategories: Array<FoodMoodTag | "全部"> = [
  "全部",
  "省钱",
  "一个人",
  "下雨天",
  "深夜",
  "想吃热的",
  "想吃清爽的",
  "想吃甜的",
  "吃饱一点",
  "不想走远",
];

export const foodRecommendations: FoodRecommendation[] = [
  {
    id: "ramen",
    name: "拉面",
    japaneseName: "ラーメン",
    category: "面类",
    priceRange: "800〜1200円",
    bestTime: ["中午", "晚上", "深夜"],
    moodTags: ["一个人", "下雨天", "深夜", "想吃热的", "吃饱一点"],
    weatherTags: ["下雨", "寒冷", "阴天"],
    description: "想快速吃点热乎的时候很稳，适合一个人进店。",
    reason: "热汤和面能让人很快恢复一点力气。",
    bestFor: ["下班后", "雨天", "不知道吃什么的时候"],
    avoidWhen: ["已经很热", "不想吃太咸"],
    image,
  },
  {
    id: "miso-ramen",
    name: "味噌拉面",
    japaneseName: "味噌ラーメン",
    category: "面类",
    priceRange: "900〜1300円",
    bestTime: ["中午", "晚上", "深夜"],
    moodTags: ["下雨天", "想吃热的", "吃饱一点", "一个人"],
    weatherTags: ["下雨", "寒冷"],
    description: "比普通拉面更厚实，冷天会特别合适。",
    reason: "味噌汤底有饱足感，适合有点累的晚上。",
    bestFor: ["寒冷天气", "想吃热汤", "需要吃饱"],
    avoidWhen: ["想吃清爽的", "已经很饱"],
    image,
  },
  {
    id: "gyudon",
    name: "牛丼",
    japaneseName: "牛丼",
    category: "米饭",
    priceRange: "500〜800円",
    bestTime: ["中午", "晚上", "深夜"],
    moodTags: ["省钱", "一个人", "深夜", "不想走远", "吃饱一点"],
    weatherTags: ["晴天", "阴天", "寒冷"],
    description: "便宜、快、容易找到，适合没有精力做决定的时候。",
    reason: "一碗饭就能解决饥饿感，深夜也比较安心。",
    bestFor: ["赶时间", "预算有限", "一个人吃饭"],
    avoidWhen: ["想慢慢吃", "想吃蔬菜多一点"],
    image,
  },
  {
    id: "curry-rice",
    name: "咖喱饭",
    japaneseName: "カレーライス",
    category: "米饭",
    priceRange: "700〜1100円",
    bestTime: ["中午", "晚上"],
    moodTags: ["省钱", "一个人", "想吃热的", "吃饱一点"],
    weatherTags: ["寒冷", "阴天", "下雨"],
    description: "日常感很强的一餐，想吃饱但不想想太多时很好。",
    reason: "热咖喱和米饭很有安全感，冷天更舒服。",
    bestFor: ["冷天", "午休", "想吃简单主食"],
    avoidWhen: ["想吃清爽的", "穿白衣服"],
    image,
  },
  {
    id: "teishoku",
    name: "定食",
    japaneseName: "定食",
    category: "主食",
    priceRange: "900〜1400円",
    bestTime: ["中午", "晚上"],
    moodTags: ["一个人", "吃饱一点", "想吃热的"],
    weatherTags: ["晴天", "阴天", "寒冷"],
    description: "饭、汤和小菜都有，适合想吃得正常一点。",
    reason: "营养和份量比较平衡，是日常吃饭的安全牌。",
    bestFor: ["工作日午餐", "晚饭", "想吃家常感"],
    avoidWhen: ["只想吃点轻的"],
    image,
  },
  {
    id: "sushi",
    name: "寿司",
    japaneseName: "寿司",
    category: "主食",
    priceRange: "1000〜2500円",
    bestTime: ["中午", "晚上"],
    moodTags: ["一个人", "想吃清爽的"],
    weatherTags: ["炎热", "晴天"],
    description: "不想吃热汤热饭时，寿司会清爽很多。",
    reason: "炎热天气里比较轻，吃完负担不大。",
    bestFor: ["热天", "想吃清爽", "轻松晚饭"],
    avoidWhen: ["预算很紧", "想吃热的"],
    image,
  },
  {
    id: "udon",
    name: "乌冬",
    japaneseName: "うどん",
    category: "面类",
    priceRange: "500〜900円",
    bestTime: ["早上", "中午", "晚上"],
    moodTags: ["省钱", "一个人", "下雨天", "想吃热的", "不想走远"],
    weatherTags: ["下雨", "寒冷", "阴天"],
    description: "温和、便宜，胃口一般的时候也比较好入口。",
    reason: "热乌冬很适合雨天和没什么精神的日子。",
    bestFor: ["雨天", "早餐", "简单晚饭"],
    avoidWhen: ["想吃重口味"],
    image,
  },
  {
    id: "soba",
    name: "荞麦面",
    japaneseName: "そば",
    category: "面类",
    priceRange: "500〜1000円",
    bestTime: ["早上", "中午", "晚上"],
    moodTags: ["省钱", "一个人", "想吃清爽的", "不想走远"],
    weatherTags: ["炎热", "晴天", "阴天"],
    description: "冷荞麦适合热天，热荞麦适合想简单吃一口。",
    reason: "清爽又不太撑，适合没有太大食欲的时候。",
    bestFor: ["炎热天气", "轻食", "一个人快吃"],
    avoidWhen: ["非常饿", "想吃甜的"],
    image,
  },
  {
    id: "oyakodon",
    name: "亲子丼",
    japaneseName: "親子丼",
    category: "米饭",
    priceRange: "700〜1100円",
    bestTime: ["中午", "晚上"],
    moodTags: ["一个人", "想吃热的", "吃饱一点"],
    weatherTags: ["寒冷", "阴天"],
    description: "鸡肉和鸡蛋盖饭，温和又有饱足感。",
    reason: "味道不刺激，适合想吃舒服一点的饭。",
    bestFor: ["普通工作日", "想吃热饭", "一个人"],
    avoidWhen: ["想吃清爽冷食"],
    image,
  },
  {
    id: "tonkatsu",
    name: "炸猪排",
    japaneseName: "とんかつ",
    category: "主食",
    priceRange: "1000〜1800円",
    bestTime: ["中午", "晚上"],
    moodTags: ["吃饱一点"],
    weatherTags: ["晴天", "阴天"],
    description: "想认真吃饱时很合适，配饭和味噌汤很有满足感。",
    reason: "适合需要一点能量的日子。",
    bestFor: ["很饿", "加班前", "想奖励自己"],
    avoidWhen: ["想吃清爽的", "不想吃油炸"],
    image,
  },
  {
    id: "konbini-onigiri",
    name: "便利店饭团",
    japaneseName: "コンビニおにぎり",
    category: "便利店",
    priceRange: "150〜400円",
    bestTime: ["早上", "中午", "深夜"],
    moodTags: ["省钱", "一个人", "深夜", "不想走远"],
    weatherTags: ["晴天", "下雨", "炎热", "寒冷"],
    description: "最省事的选择，适合真的不想走远的时候。",
    reason: "买得到、吃得快，也不会太有负担。",
    bestFor: ["早上赶时间", "深夜", "预算有限"],
    avoidWhen: ["想好好坐下来吃"],
    image,
  },
  {
    id: "konbini-bento",
    name: "便利店便当",
    japaneseName: "コンビニ弁当",
    category: "便利店",
    priceRange: "500〜900円",
    bestTime: ["中午", "晚上", "深夜"],
    moodTags: ["省钱", "一个人", "深夜", "不想走远", "吃饱一点"],
    weatherTags: ["下雨", "寒冷", "阴天"],
    description: "不想排队、不想选店时，便利店便当很实际。",
    reason: "选择多，热一下就能吃，雨天尤其省心。",
    bestFor: ["雨天", "回家路上", "深夜"],
    avoidWhen: ["想吃现做的"],
    image,
  },
  {
    id: "oden",
    name: "关东煮",
    japaneseName: "おでん",
    category: "便利店",
    priceRange: "300〜800円",
    bestTime: ["晚上", "深夜"],
    moodTags: ["省钱", "下雨天", "深夜", "想吃热的", "不想走远"],
    weatherTags: ["下雨", "寒冷"],
    description: "冷天在便利店买几样就很舒服。",
    reason: "热汤和萝卜、鸡蛋很适合晚上慢慢吃。",
    bestFor: ["冷天", "深夜", "想吃热汤"],
    avoidWhen: ["炎热天气", "想吃主食"],
    image,
  },
  {
    id: "yakiniku",
    name: "烧肉",
    japaneseName: "焼肉",
    category: "聚餐",
    priceRange: "2500〜5000円",
    bestTime: ["晚上"],
    moodTags: ["吃饱一点"],
    weatherTags: ["晴天", "阴天"],
    description: "适合想吃得开心一点，或者和朋友一起吃。",
    reason: "份量和满足感都高，更像一顿小奖励。",
    bestFor: ["朋友聚餐", "想吃肉", "周末晚上"],
    avoidWhen: ["预算紧", "只想一个人快吃"],
    image,
  },
  {
    id: "izakaya-small-dishes",
    name: "居酒屋小菜",
    japaneseName: "居酒屋のおつまみ",
    category: "聚餐",
    priceRange: "1500〜3500円",
    bestTime: ["晚上", "深夜"],
    moodTags: ["深夜", "一个人"],
    weatherTags: ["晴天", "阴天", "寒冷"],
    description: "不想吃正餐时，可以点几样小菜慢慢吃。",
    reason: "适合晚上想放松一点，但不想吃太撑。",
    bestFor: ["下班后", "轻松聊天", "一个人小酌"],
    avoidWhen: ["很饿", "想省钱"],
    image,
  },
  {
    id: "nabe",
    name: "火锅",
    japaneseName: "鍋",
    category: "主食",
    priceRange: "1200〜3000円",
    bestTime: ["晚上"],
    moodTags: ["下雨天", "想吃热的", "吃饱一点"],
    weatherTags: ["下雨", "寒冷"],
    description: "冷天或雨天最适合，家里做也可以。",
    reason: "热汤、蔬菜和肉都在一起，吃完很暖。",
    bestFor: ["寒冷晚上", "朋友一起", "在家吃饭"],
    avoidWhen: ["炎热天气", "赶时间"],
    image,
  },
  {
    id: "cold-noodles",
    name: "冷面",
    japaneseName: "冷麺",
    category: "面类",
    priceRange: "800〜1300円",
    bestTime: ["中午", "晚上"],
    moodTags: ["想吃清爽的"],
    weatherTags: ["炎热", "晴天"],
    description: "热到没胃口的时候，冷面会轻松很多。",
    reason: "冰凉、酸甜或清爽的味道适合夏天。",
    bestFor: ["炎热天气", "没胃口", "想吃凉的"],
    avoidWhen: ["寒冷天气", "想吃热汤"],
    image,
  },
  {
    id: "omurice",
    name: "蛋包饭",
    japaneseName: "オムライス",
    category: "米饭",
    priceRange: "900〜1500円",
    bestTime: ["中午", "晚上"],
    moodTags: ["一个人", "吃饱一点"],
    weatherTags: ["晴天", "阴天"],
    description: "有点洋食感，又不会太正式。",
    reason: "适合想吃温柔一点、带点怀旧感的饭。",
    bestFor: ["咖啡店午餐", "一个人", "普通晚饭"],
    avoidWhen: ["想吃清爽的"],
    image,
  },
  {
    id: "hamburg-steak",
    name: "汉堡排",
    japaneseName: "ハンバーグ",
    category: "主食",
    priceRange: "1000〜1800円",
    bestTime: ["中午", "晚上"],
    moodTags: ["吃饱一点", "想吃热的"],
    weatherTags: ["寒冷", "阴天"],
    description: "想吃肉但不想吃烧肉时，汉堡排很刚好。",
    reason: "热乎、下饭，适合补一点能量。",
    bestFor: ["晚饭", "想吃洋食", "工作日"],
    avoidWhen: ["想吃轻食"],
    image,
  },
  {
    id: "takoyaki",
    name: "章鱼烧",
    japaneseName: "たこ焼き",
    category: "轻食",
    priceRange: "500〜900円",
    bestTime: ["下午", "晚上"],
    moodTags: ["省钱", "一个人", "想吃热的"],
    weatherTags: ["晴天", "阴天"],
    description: "不算正餐，但适合想吃点热乎小东西。",
    reason: "边走边买也可以，有一点生活感。",
    bestFor: ["散步后", "小饿", "想吃小吃"],
    avoidWhen: ["非常饿", "想吃清爽的"],
    image,
  },
  {
    id: "crepe",
    name: "可丽饼",
    japaneseName: "クレープ",
    category: "甜点",
    priceRange: "500〜900円",
    bestTime: ["下午", "晚上"],
    moodTags: ["想吃甜的", "一个人"],
    weatherTags: ["晴天", "阴天"],
    description: "想吃甜的但不想坐下来时，可以买一个慢慢走。",
    reason: "适合作为今天的小奖励。",
    bestFor: ["下午", "散步", "想吃甜点"],
    avoidWhen: ["想吃正餐", "下雨很大"],
    image,
  },
  {
    id: "donut",
    name: "甜甜圈",
    japaneseName: "ドーナツ",
    category: "甜点",
    priceRange: "200〜600円",
    bestTime: ["早上", "中午"],
    moodTags: ["省钱", "一个人", "想吃甜的", "不想走远"],
    weatherTags: ["晴天", "下雨", "阴天"],
    description: "配咖啡很方便，适合早上或下午想补一点糖分。",
    reason: "轻松、便宜，也不需要认真选店。",
    bestFor: ["咖啡时间", "早上", "小奖励"],
    avoidWhen: ["想吃饱一点"],
    image,
  },
  {
    id: "coffee-bread",
    name: "咖啡 + 面包",
    japaneseName: "コーヒーとパン",
    category: "轻食",
    priceRange: "400〜900円",
    bestTime: ["早上", "中午"],
    moodTags: ["省钱", "一个人", "不想走远"],
    weatherTags: ["晴天", "阴天", "下雨"],
    description: "早上不知道吃什么时，这个组合很稳。",
    reason: "不重，也能让一天慢慢开始。",
    bestFor: ["早上", "赶时间", "咖啡店"],
    avoidWhen: ["很饿", "想吃热饭"],
    image,
  },
  {
    id: "sandwich",
    name: "三明治",
    japaneseName: "サンドイッチ",
    category: "轻食",
    priceRange: "300〜800円",
    bestTime: ["早上", "中午"],
    moodTags: ["省钱", "一个人", "想吃清爽的", "不想走远"],
    weatherTags: ["晴天", "炎热", "阴天"],
    description: "轻一点，不太需要坐下来认真吃。",
    reason: "适合早上或午休时间短的时候。",
    bestFor: ["早上", "午休", "热天"],
    avoidWhen: ["想吃热的", "非常饿"],
    image,
  },
  {
    id: "fried-rice",
    name: "炒饭",
    japaneseName: "チャーハン",
    category: "米饭",
    priceRange: "700〜1100円",
    bestTime: ["中午", "晚上"],
    moodTags: ["省钱", "一个人", "吃饱一点"],
    weatherTags: ["晴天", "阴天"],
    description: "中式店里的稳定选择，吃得快也吃得饱。",
    reason: "不想复杂点菜时，一盘炒饭很省心。",
    bestFor: ["午餐", "一个人", "想吃米饭"],
    avoidWhen: ["想吃清爽的"],
    image,
  },
  {
    id: "chinese-food",
    name: "中华料理",
    japaneseName: "中華料理",
    category: "主食",
    priceRange: "900〜1800円",
    bestTime: ["中午", "晚上"],
    moodTags: ["吃饱一点", "想吃热的"],
    weatherTags: ["寒冷", "阴天", "下雨"],
    description: "选择多，适合想吃热菜热饭的时候。",
    reason: "炒菜、汤面、盖饭都能选，灵活度很高。",
    bestFor: ["晚饭", "朋友一起", "想吃热菜"],
    avoidWhen: ["只想轻食"],
    image,
  },
  {
    id: "korean-food",
    name: "韓国料理",
    japaneseName: "韓国料理",
    category: "主食",
    priceRange: "1000〜2200円",
    bestTime: ["中午", "晚上"],
    moodTags: ["想吃热的", "吃饱一点"],
    weatherTags: ["寒冷", "下雨"],
    description: "想吃辣一点、热一点的时候可以考虑。",
    reason: "汤和拌饭类都适合冷天或雨天。",
    bestFor: ["冷天", "想吃辣", "晚饭"],
    avoidWhen: ["不想重口味"],
    image,
  },
  {
    id: "vegetable-salad",
    name: "蔬菜沙拉",
    japaneseName: "野菜サラダ",
    category: "轻食",
    priceRange: "500〜1200円",
    bestTime: ["早上", "中午", "晚上"],
    moodTags: ["想吃清爽的", "一个人"],
    weatherTags: ["炎热", "晴天"],
    description: "想吃轻一点、清爽一点的时候很合适。",
    reason: "热天或胃口不大时，沙拉不会太有负担。",
    bestFor: ["炎热天气", "轻食", "想补蔬菜"],
    avoidWhen: ["很饿", "想吃热的"],
    image,
  },
  {
    id: "kaisendon",
    name: "海鲜丼",
    japaneseName: "海鮮丼",
    category: "米饭",
    priceRange: "1200〜2500円",
    bestTime: ["中午", "晚上"],
    moodTags: ["想吃清爽的", "吃饱一点"],
    weatherTags: ["炎热", "晴天"],
    description: "比普通盖饭清爽，但也能吃饱。",
    reason: "适合想吃米饭，又不想吃太热太重的时候。",
    bestFor: ["热天", "午餐", "想吃海鲜"],
    avoidWhen: ["预算紧", "想吃热汤"],
    image,
  },
  {
    id: "home-noodles",
    name: "家里简单煮面",
    japaneseName: "家で簡単な麺",
    category: "家里",
    priceRange: "200〜600円",
    bestTime: ["早上", "中午", "晚上", "深夜"],
    moodTags: ["省钱", "一个人", "深夜", "想吃热的", "不想走远"],
    weatherTags: ["下雨", "寒冷", "阴天"],
    description: "不想出门时，在家煮一碗面就够了。",
    reason: "省钱、省力，也不用被天气影响。",
    bestFor: ["雨天", "深夜", "不想出门"],
    avoidWhen: ["想出去换心情"],
    image,
  },
];
